// Regenerates `lib/src/art/kilo_art.g.dart` from `assets/`.
//
//     dart run tool/build_art.dart
//
// The artwork is embedded rather than bundled as assets because an empty
// state that flashes blank while its illustration loads off the bundle is
// worse than one with no illustration at all. `test/art_test.dart` fails if
// this output has drifted from the folder.
import 'dart:io';

const _sentinels = [
  '#FF00E0', '#FF00E1', '#FF00E2', '#FF00E3',
  '#FF00E4', '#FF00E5', '#FF00E6', '#FF00E7',
];

void main() {
  final root = Directory('assets');
  if (!root.existsSync()) {
    stderr.writeln('run me from packages/bel_design');
    exit(2);
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/build_art.dart — do not edit by hand.')
    ..writeln('// Edit the SVG under assets/ and re-run the generator.')
    ..writeln('//')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln();

  _emit(buffer, 'KArt', 'illustrations', '''
/// The spot illustrations. Every empty, error and success state in the
/// product draws from this list rather than inventing its own picture.''');
  _emit(buffer, 'KSceneArt', 'scenes', '''
/// Full-bleed hero artwork, drawn wide (800×400) and cropped with
/// `BoxFit.cover`.''');

  File('lib/src/art/kilo_art.g.dart').writeAsStringSync(buffer.toString());
  stdout.writeln('kilo_art.g.dart written');
}

void _emit(StringBuffer out, String enumName, String dir, String doc) {
  final files = Directory('assets/$dir')
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.svg'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  out.writeln(doc);
  out.writeln('enum $enumName {');
  for (final file in files) {
    final stem = file.uri.pathSegments.last.replaceAll('.svg', '');
    final svg = _minify(file.readAsStringSync());
    _check(file.path, svg);
    out.writeln("  ${_camel(stem)}(r'''$svg'''),");
  }
  out
    ..writeln('  ;')
    ..writeln()
    ..writeln('  const $enumName(this.source);')
    ..writeln()
    ..writeln('  /// The SVG, still in the sentinel palette. Substituted for')
    ..writeln('  /// real tokens at paint time by `KArtPalette.paint`.')
    ..writeln('  final String source;')
    ..writeln('}')
    ..writeln();
}

/// Whitespace between tags only — never inside an attribute, where it would
/// corrupt a `d=` or a `stroke-dasharray`.
String _minify(String svg) => svg
    .replaceAll(RegExp(r'<!--.*?-->', dotAll: true), '')
    .replaceAll(RegExp(r'>\s+<'), '><')
    .trim();

void _check(String path, String svg) {
  final colours = RegExp('#[0-9A-Fa-f]{3,8}')
      .allMatches(svg)
      .map((m) => m[0]!.toUpperCase())
      .toSet();
  final stray = colours.where((c) => !_sentinels.contains(c)).toList();
  if (stray.isNotEmpty) {
    stderr.writeln('$path uses non-token colours: ${stray.join(', ')}');
    stderr.writeln('see assets/README.md for the sentinel palette');
    exit(1);
  }
}

String _camel(String kebab) {
  final parts = kebab.split(RegExp('[-_]'));
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}
