import 'package:bel_domain/bel_domain.dart';

import '../json/json_codec.dart';

/// One departure the traveller could move to, priced (§8.1).
final class ChangeOptionDto {
  const ChangeOptionDto({
    required this.departureId,
    required this.departsAt,
    required this.arrivesAt,
    required this.fare,
    required this.seatsAvailable,
    this.fee,
    this.fareDifference,
    this.owed,
    this.refusalCode,
    this.refusalParams = const {},
  });

  final String departureId;
  final DateTime departsAt;

  /// On every row: the question being asked is when they arrive.
  final DateTime arrivesAt;

  final Money fare;
  final int seatsAvailable;

  /// The operator's charge for changing, and what the new coach costs above
  /// the old one. Both on the row **before selection**, which is what §8.1's
  /// mock asks for — somebody scanning a list is comparing prices, and a
  /// screen that prices only the row you tapped makes them tap five times.
  final Money? fee;
  final Money? fareDifference;

  /// Fee plus difference. Zero means one tap and it is done.
  final Money? owed;

  /// Why this row cannot be taken. Shown rather than hidden: a departure
  /// missing from a list is a departure somebody telephones to ask about.
  final String? refusalCode;
  final Map<String, Object?> refusalParams;

  bool get isTakeable => refusalCode == null;
  bool get isFree => (owed?.minor ?? 0) == 0;

  Map<String, Object?> toJson() => Wire.compact({
    'departureId': departureId,
    'departsAt': Wire.instant(departsAt),
    'arrivesAt': Wire.instant(arrivesAt),
    'fare': Wire.money(fare),
    'seatsAvailable': seatsAvailable,
    'fee': fee == null ? null : Wire.money(fee!),
    'fareDifference': fareDifference == null
        ? null
        : Wire.money(fareDifference!),
    'owed': owed == null ? null : Wire.money(owed!),
    'refusalCode': refusalCode,
    'refusalParams': refusalParams.isEmpty ? null : refusalParams,
  });

  factory ChangeOptionDto.fromJson(
    Map<String, Object?> json,
  ) => ChangeOptionDto(
    departureId: Wire.requireString(json['departureId'], 'departureId'),
    departsAt: Wire.readInstant(json['departsAt'], field: 'departsAt'),
    arrivesAt: Wire.readInstant(json['arrivesAt'], field: 'arrivesAt'),
    fare: Wire.readMoney(json['fare'], field: 'fare'),
    seatsAvailable: json['seatsAvailable'] as int? ?? 0,
    fee: json['fee'] == null ? null : Wire.readMoney(json['fee'], field: 'fee'),
    fareDifference: json['fareDifference'] == null
        ? null
        : Wire.readMoney(json['fareDifference'], field: 'fareDifference'),
    owed: json['owed'] == null
        ? null
        : Wire.readMoney(json['owed'], field: 'owed'),
    refusalCode: json['refusalCode'] as String?,
    refusalParams:
        (json['refusalParams'] as Map?)?.cast<String, Object?>() ?? const {},
  );
}

/// The whole change screen, in one response.
final class ChangeOptionsDto {
  const ChangeOptionsDto({
    required this.bookingRef,
    required this.originCity,
    required this.destinationCity,
    required this.seatsNeeded,
    required this.currentDepartureId,
    required this.currentDepartsAt,
    required this.paidFare,
    required this.options,
    this.policyLines = const [],
    this.involuntary = false,
    this.refusalCode,
    this.refusalParams = const {},
  });

  final String bookingRef;
  final String originCity;
  final String destinationCity;

  /// The party. Three people who booked together move together or not at all.
  final int seatsNeeded;

  final String currentDepartureId;
  final DateTime currentDepartsAt;

  /// What they paid, per seat. Every difference on the screen is against it.
  final Money paidFare;

  final List<ChangeOptionDto> options;

  /// The terms as `key|arg` lines, generated by the domain from the stored
  /// numbers — the same sentences the operator's policy screen renders.
  final List<String> policyLines;

  /// True when the operator already caused a change to this booking. Every
  /// row is then free, whatever the window says (ADR-0016).
  final bool involuntary;

  /// Set when no change is possible at all. The screen renders the reason
  /// and no rows.
  final String? refusalCode;
  final Map<String, Object?> refusalParams;

  bool get isOpen => refusalCode == null;

  Map<String, Object?> toJson() => Wire.compact({
    'bookingRef': bookingRef,
    'originCity': originCity,
    'destinationCity': destinationCity,
    'seatsNeeded': seatsNeeded,
    'currentDepartureId': currentDepartureId,
    'currentDepartsAt': Wire.instant(currentDepartsAt),
    'paidFare': Wire.money(paidFare),
    'options': [for (final o in options) o.toJson()],
    'policyLines': policyLines,
    'involuntary': involuntary,
    'refusalCode': refusalCode,
    'refusalParams': refusalParams.isEmpty ? null : refusalParams,
  });

  factory ChangeOptionsDto.fromJson(
    Map<String, Object?> json,
  ) => ChangeOptionsDto(
    bookingRef: Wire.requireString(json['bookingRef'], 'bookingRef'),
    originCity: Wire.requireString(json['originCity'], 'originCity'),
    destinationCity: Wire.requireString(
      json['destinationCity'],
      'destinationCity',
    ),
    seatsNeeded: json['seatsNeeded'] as int? ?? 1,
    currentDepartureId: Wire.requireString(
      json['currentDepartureId'],
      'currentDepartureId',
    ),
    currentDepartsAt: Wire.readInstant(
      json['currentDepartsAt'],
      field: 'currentDepartsAt',
    ),
    paidFare: Wire.readMoney(json['paidFare'], field: 'paidFare'),
    options: Wire.readList(
      json['options'],
      ChangeOptionDto.fromJson,
      field: 'options',
    ),
    policyLines: [
      for (final line in (json['policyLines'] as List? ?? const [])) '$line',
    ],
    involuntary: json['involuntary'] as bool? ?? false,
    refusalCode: json['refusalCode'] as String?,
    refusalParams:
        (json['refusalParams'] as Map?)?.cast<String, Object?>() ?? const {},
  );
}

/// Taking one.
final class ChangeRequest {
  const ChangeRequest({required this.departureId});

  final String departureId;

  Map<String, Object?> toJson() => {'departureId': departureId};

  factory ChangeRequest.fromJson(Map<String, Object?> json) => ChangeRequest(
    departureId: Wire.requireString(json['departureId'], 'departureId'),
  );
}

/// What happened when they tapped.
final class ChangeAppliedDto {
  const ChangeAppliedDto({
    required this.bookingRef,
    required this.departureId,
    required this.departsAt,
    this.seatLabels = const [],
  });

  final String bookingRef;
  final String departureId;
  final DateTime departsAt;

  /// The new seats. A family of four keeps four, and the numbers change —
  /// which is exactly what somebody needs to read before boarding.
  final List<String> seatLabels;

  Map<String, Object?> toJson() => Wire.compact({
    'bookingRef': bookingRef,
    'departureId': departureId,
    'departsAt': Wire.instant(departsAt),
    'seatLabels': seatLabels,
  });

  factory ChangeAppliedDto.fromJson(Map<String, Object?> json) =>
      ChangeAppliedDto(
        bookingRef: Wire.requireString(json['bookingRef'], 'bookingRef'),
        departureId: Wire.requireString(json['departureId'], 'departureId'),
        departsAt: Wire.readInstant(json['departsAt'], field: 'departsAt'),
        seatLabels: (json['seatLabels'] as List?)?.cast<String>() ?? const [],
      );
}

/// A change waiting to be paid for.
///
/// The seats are already held by this order — it is a promise with an expiry,
/// not an intention — and the booking has not moved. What the screen does
/// with it is show the amount, the deadline, and a way to pay; what it must
/// never do is tell somebody they have changed departure, because until the
/// money lands they have not.
final class ChangeOrderDto {
  const ChangeOrderDto({
    required this.id,
    required this.bookingId,
    required this.bookingRef,
    required this.departureId,
    required this.departsAt,
    required this.owed,
    required this.expiresAt,
    required this.state,
    this.fee,
    this.fareDifference,
    this.seatLabels = const [],
    this.applied,
  });

  final String id;
  final String bookingId;
  final String bookingRef;
  final String departureId;
  final DateTime departsAt;

  /// What is owed, exactly. Quoted once and stored, so the amount on the
  /// screen and the amount on the prompt cannot differ.
  final Money owed;

  final DateTime expiresAt;

  /// `awaiting_payment` or `applied`. The second happens when the difference
  /// turned out to be nothing between the list and the tap — the change is
  /// simply made, and [applied] carries what happened.
  final String state;

  final Money? fee;
  final Money? fareDifference;
  final List<String> seatLabels;
  final ChangeAppliedDto? applied;

  bool get isAwaitingPayment => state == 'awaiting_payment';
  bool get isApplied => state == 'applied';

  Map<String, Object?> toJson() => Wire.compact({
    'id': id,
    'bookingId': bookingId,
    'bookingRef': bookingRef,
    'departureId': departureId,
    'departsAt': Wire.instant(departsAt),
    'owed': Wire.money(owed),
    'expiresAt': Wire.instant(expiresAt),
    'state': state,
    'fee': fee == null ? null : Wire.money(fee!),
    'fareDifference': fareDifference == null
        ? null
        : Wire.money(fareDifference!),
    'seatLabels': seatLabels,
    'applied': applied?.toJson(),
  });

  factory ChangeOrderDto.fromJson(Map<String, Object?> json) => ChangeOrderDto(
    id: Wire.requireString(json['id'], 'id'),
    bookingId: Wire.requireString(json['bookingId'], 'bookingId'),
    bookingRef: Wire.requireString(json['bookingRef'], 'bookingRef'),
    departureId: Wire.requireString(json['departureId'], 'departureId'),
    departsAt: Wire.readInstant(json['departsAt'], field: 'departsAt'),
    owed: Wire.readMoney(json['owed'], field: 'owed'),
    expiresAt: Wire.readInstant(json['expiresAt'], field: 'expiresAt'),
    state: json['state'] as String? ?? 'awaiting_payment',
    fee: json['fee'] == null ? null : Wire.readMoney(json['fee'], field: 'fee'),
    fareDifference: json['fareDifference'] == null
        ? null
        : Wire.readMoney(json['fareDifference'], field: 'fareDifference'),
    seatLabels: (json['seatLabels'] as List?)?.cast<String>() ?? const [],
    applied: json['applied'] == null
        ? null
        : ChangeAppliedDto.fromJson(
            (json['applied'] as Map).cast<String, Object?>(),
          ),
  );
}
