---
apiVersion: v1
kind: Service
metadata:
  name: bel-admin
  namespace: billetenligne
  labels:
    app: bel-admin
spec:
  type: ClusterIP
  selector:
    app: bel-admin
  ports:
    - name: http
      port: 8080
      targetPort: http
