import 'package:bel_domain/bel_domain.dart';

import '../json/json_codec.dart';

/// What cancelling a booking would give back — or why it cannot.
///
/// Distinct from the traveller-facing `RefundQuoteDto`, which models a quote
/// that exists. This one models the *question*: the counter asks about a
/// reference and gets either terms and an amount, or the reason there is
/// none. Collapsing the two would force a fake quote of zero, which reads as
/// a bug to the person being told it.
///
/// The terms it was sold
/// with.
///
/// The number a vendor reads aloud before anybody agrees to anything. It is
/// computed by `quoteRefund` on the server and executed by the same function
/// a moment later, so the sentence at the counter and the money out of the
/// drawer cannot disagree (ADR-0004).
final class RefundOfferDto {
  const RefundOfferDto({
    required this.bookingRef,
    required this.state,
    required this.departsAt,
    required this.fare,
    required this.serviceFee,
    this.refundable,
    this.retained,
    this.rateBps,
    this.destination,
    this.processingHours,
    this.involuntary = false,
    this.policyName,
    this.policyLines = const [],
    this.failureCode,
  });

  final String bookingRef;
  final String state;
  final DateTime departsAt;
  final Money fare;
  final Money serviceFee;

  /// Null when the terms give nothing back. [failureCode] then says why, and
  /// the counter shows the reason rather than "0 FCFA" — which reads as a bug
  /// to the person being told it.
  final Money? refundable;
  final Money? retained;
  final int? rateBps;
  final String? destination;
  final int? processingHours;

  /// True when the operator caused this. Bypasses their policy entirely — the
  /// platform floor (ADR-0015 rule 4).
  final bool involuntary;

  final String? policyName;

  /// The terms as `key|arg` lines, generated by the domain from the stored
  /// numbers. The same sentences the traveller was shown before paying.
  final List<String> policyLines;

  final String? failureCode;

  bool get isRefundable => (refundable?.minor ?? 0) > 0;

  /// Whether the money is collected at a counter rather than sent somewhere.
  bool get isCollectedInPerson =>
      destination == 'agencyCash' || destination == 'travellerChoice';

  factory RefundOfferDto.fromJson(Map<String, Object?> json) => RefundOfferDto(
    bookingRef: Wire.requireString(json['bookingRef'], 'bookingRef'),
    state: Wire.requireString(json['state'], 'state'),
    departsAt: Wire.readInstant(json['departsAt'], field: 'departsAt'),
    fare: Wire.readMoney(json['fare'], field: 'fare'),
    serviceFee: Wire.readMoney(json['serviceFee'], field: 'serviceFee'),
    refundable: json['refundable'] == null
        ? null
        : Wire.readMoney(json['refundable'], field: 'refundable'),
    retained: json['retained'] == null
        ? null
        : Wire.readMoney(json['retained'], field: 'retained'),
    rateBps: json['rateBps'] as int?,
    destination: json['destination'] as String?,
    processingHours: json['processingHours'] as int?,
    involuntary: json['involuntary'] as bool? ?? false,
    policyName: json['policyName'] as String?,
    policyLines: [
      for (final line in (json['policyLines'] as List? ?? const [])) '$line',
    ],
    failureCode: json['failureCode'] as String?,
  );
}

/// A refund that has been approved and is waiting to be collected.
final class IssuedRefundDto {
  const IssuedRefundDto({
    required this.id,
    required this.bookingRef,
    required this.amount,
    required this.destination,
    required this.state,
    this.claimCode,
    this.claimExpiresAt,
  });

  final String id;
  final String bookingRef;
  final Money amount;
  final String destination;
  final String state;

  /// The six characters the traveller shows at the counter. Null for a
  /// destination that does not end at one.
  final String? claimCode;
  final DateTime? claimExpiresAt;

  factory IssuedRefundDto.fromJson(Map<String, Object?> json) =>
      IssuedRefundDto(
        id: Wire.requireString(json['id'], 'id'),
        bookingRef: Wire.requireString(json['bookingRef'], 'bookingRef'),
        amount: Wire.readMoney(json['amount'], field: 'amount'),
        destination: Wire.requireString(json['destination'], 'destination'),
        state: Wire.requireString(json['state'], 'state'),
        claimCode: json['claimCode'] as String?,
        claimExpiresAt: json['claimExpiresAt'] == null
            ? null
            : Wire.readInstant(json['claimExpiresAt'], field: 'claimExpiresAt'),
      );
}

/// A claim just paid out of a drawer.
final class ClaimedRefundDto {
  const ClaimedRefundDto({
    required this.id,
    required this.bookingRef,
    required this.amount,
    required this.stationId,
  });

  final String id;
  final String bookingRef;
  final Money amount;
  final String stationId;

  factory ClaimedRefundDto.fromJson(Map<String, Object?> json) =>
      ClaimedRefundDto(
        id: Wire.requireString(json['id'], 'id'),
        bookingRef: Wire.requireString(json['bookingRef'], 'bookingRef'),
        amount: Wire.readMoney(json['amount'], field: 'amount'),
        stationId: Wire.requireString(json['stationId'], 'stationId'),
      );
}
