// Compiles `packages/bel_design/assets/` into the two places that draw it.
//
//     dart run tool/build_art.dart
//
// One folder of SVG, two consumers with nothing in common: the Flutter apps,
// which paint it with `flutter_svg`, and the API, which inlines it into
// server-rendered HTML. The artwork is embedded in both rather than loaded,
// because an empty state that flashes blank while its illustration arrives is
// worse than one with no illustration, and a storefront has to render before
// anything else has loaded at all.
//
// This lives at the repo root rather than inside either package, because a
// generator that belongs to one of two consumers always ends up reaching
// across a boundary it should not know about.
//
// `packages/bel_design/test/art_test.dart` and the API's own test fail if
// either output has drifted from the folder.
import 'dart:io';

const _sentinels = [
  '#FF00E0',
  '#FF00E1',
  '#FF00E2',
  '#FF00E3',
  '#FF00E4',
  '#FF00E5',
  '#FF00E6',
  '#FF00E7',
];

const _assets = 'packages/bel_design/assets';

void main() {
  if (!Directory(_assets).existsSync()) {
    stderr.writeln('run me from the repository root');
    exit(2);
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/build_art.dart — do not edit by hand.')
    ..writeln('// Edit the SVG under assets/ and re-run the generator.')
    ..writeln('//')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln();

  _emit(buffer, 'KArt', 'illustrations', '''
/// The spot illustrations. Every empty, error and success state in the
/// product draws from this list rather than inventing its own picture.''');
  _emit(buffer, 'KSceneArt', 'scenes', '''
/// Full-bleed hero artwork, drawn wide and cropped with `BoxFit.cover`.''');

  File(
    'packages/bel_design/lib/src/art/kilo_art.g.dart',
  ).writeAsStringSync(buffer.toString());
  _emitServer();
  stdout.writeln('artwork written for bel_design and services/api');
}

/// The API's copy: plain Dart, no Flutter, no enums to import.
///
/// The server substitutes the sentinel palette for **CSS custom properties**
/// rather than for literal colours. An inline SVG inherits them from the
/// document, so one embedded drawing follows the page's light/dark media
/// query *and* the operator's own accent without the server knowing either.
void _emitServer() {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/build_art.dart — do not edit by hand.')
    ..writeln('// Edit the SVG under packages/bel_design/assets/ and re-run.')
    ..writeln('//')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The artwork, ready to inline into a server-rendered page.')
    ..writeln('///')
    ..writeln('/// Values are the raw SVG in the sentinel palette; call')
    ..writeln('/// [Artwork.css] to swap it for the custom properties the')
    ..writeln('/// page defines.')
    ..writeln('abstract final class Artwork {');

  for (final dir in ['illustrations', 'scenes']) {
    for (final file in _files(dir)) {
      final stem = file.uri.pathSegments.last.replaceAll('.svg', '');
      final svg = _minify(file.readAsStringSync());
      _check(file.path, svg);
      out.writeln("  static const ${_camel(stem)} = r'''$svg''';");
    }
  }

  out
    ..writeln()
    ..writeln('  /// Sentinel -> the CSS custom property that replaces it.')
    ..writeln('  static const palette = <String, String>{');
  for (var i = 0; i < _sentinels.length; i++) {
    out.writeln("    '${_sentinels[i]}': 'var(${_cssVars[i]})',");
  }
  out
    ..writeln('  };')
    ..writeln()
    ..writeln('  /// The drawing, wired to the page.')
    ..writeln('  static String css(String svg) {')
    ..writeln('    var out = svg;')
    ..writeln(
      '    palette.forEach((from, to) => out = out.replaceAll(from, to));',
    )
    ..writeln('    return out;')
    ..writeln('  }')
    ..writeln('}');

  File(
    'services/api/lib/src/infrastructure/web/artwork.g.dart',
  ).writeAsStringSync(out.toString());
}

/// The custom property each sentinel becomes.
///
/// The brand slot resolves through `--art-brand` *before* falling back to the
/// operator's accent. On the storefront hero the accent is already the
/// background, so hills painted in it would be invisible; the hero overrides
/// `--art-brand` to a translucent white and the drawing becomes a silhouette,
/// while everywhere else on the page it is simply the company's colour.
const _cssVars = [
  '--art-ink',
  '--art-muted',
  '--art-brand,var(--accent)',
  '--art-wash',
  '--art-accent',
  '--art-accent-wash',
  '--art-surface',
  '--art-line',
];

List<File> _files(String dir) =>
    Directory('$_assets/$dir')
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.svg'))
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

void _emit(StringBuffer out, String enumName, String dir, String doc) {
  final files = _files(dir);

  out.writeln(doc);
  out.writeln('enum $enumName {');
  for (final file in files) {
    final stem = file.uri.pathSegments.last.replaceAll('.svg', '');
    final svg = _minify(file.readAsStringSync());
    _check(file.path, svg);
    out.writeln("  ${_camel(stem)}(r'''$svg'''),");
  }
  out
    ..writeln('  ;')
    ..writeln()
    ..writeln('  const $enumName(this.source);')
    ..writeln()
    ..writeln('  /// The SVG, still in the sentinel palette. Substituted for')
    ..writeln('  /// real tokens at paint time by `KArtPalette.paint`.')
    ..writeln('  final String source;')
    ..writeln('}')
    ..writeln();
}

/// Whitespace between tags only — never inside an attribute, where it would
/// corrupt a `d=` or a `stroke-dasharray`.
String _minify(String svg) => svg
    .replaceAll(RegExp(r'<!--.*?-->', dotAll: true), '')
    .replaceAll(RegExp(r'>\s+<'), '><')
    .trim();

void _check(String path, String svg) {
  final colours = RegExp(
    '#[0-9A-Fa-f]{3,8}',
  ).allMatches(svg).map((m) => m[0]!.toUpperCase()).toSet();
  final stray = colours.where((c) => !_sentinels.contains(c)).toList();
  if (stray.isNotEmpty) {
    stderr.writeln('$path uses non-token colours: ${stray.join(', ')}');
    stderr.writeln('see assets/README.md for the sentinel palette');
    exit(1);
  }
}

String _camel(String kebab) {
  final parts = kebab.split(RegExp('[-_]'));
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}
