-- 0001_foundation — tenancy, catalogue, fleet, scheduling.
--
-- Conventions used throughout these migrations:
--
--   * Money is ALWAYS (amount_minor BIGINT, currency CHAR(3)). Never NUMERIC,
--     never a float. XAF is zero-decimal, so 9 000 XAF is 9000.
--   * Every tenant-scoped table carries operator_id and has an RLS policy.
--     RLS is the real boundary (ADR-0011) — if application code forgets a
--     filter, the database still refuses.
--   * Timestamps are TIMESTAMPTZ, stored UTC. Local time is how a departure
--     ends up an hour out.
--   * IDs are UUIDs generated by the database, except booking_ref which is a
--     short human-readable code (Crockford base32).

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── Tenancy ─────────────────────────────────────────────────────────────────

CREATE TYPE operator_status AS ENUM (
  'registered', 'application_draft', 'under_review', 'kyb_verifying',
  'info_requested', 'approved', 'active', 'suspended', 'offboarding',
  'offboarded', 'rejected'
);

CREATE TABLE operators (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code                  TEXT NOT NULL UNIQUE,
  legal_name            TEXT NOT NULL,
  trading_name          TEXT,
  market_code           TEXT NOT NULL,
  status                operator_status NOT NULL DEFAULT 'registered',

  rccm_number           TEXT,
  tax_id                TEXT,

  -- Netted at source rather than invoiced, so we never chase an operator for
  -- money (04-payments.md §6.2).
  commission_bps        INTEGER NOT NULL DEFAULT 500,
  payout_frequency_days INTEGER NOT NULL DEFAULT 7,
  settlement_account_id UUID,

  -- Vitrine (03-operator-lifecycle.md §2.4). Bounded on purpose: an accent
  -- from a closed set of eight, never a free colour picker.
  logo_asset            TEXT,
  accent_hue            TEXT NOT NULL DEFAULT 'foret',
  header_pattern        TEXT NOT NULL DEFAULT 'flat',
  title_fr              TEXT,
  title_en              TEXT,
  tagline_fr            TEXT,
  tagline_en            TEXT,
  cover_asset           TEXT,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at           TIMESTAMPTZ,
  suspended_at          TIMESTAMPTZ,
  suspended_reason      TEXT,
  offboarded_at         TIMESTAMPTZ,

  CONSTRAINT operators_commission_sane CHECK (commission_bps BETWEEN 0 AND 3000),
  CONSTRAINT operators_accent_known CHECK (accent_hue IN
    ('foret','laterite','indigo','brique','prune','ocean','olive','ardoise'))
);

CREATE INDEX operators_status_idx ON operators (status) WHERE status = 'active';

-- ── Identity and staff ──────────────────────────────────────────────────────

CREATE TABLE user_accounts (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Firebase UID (ADR-0018). Authorisation is ours; authentication is theirs.
  auth_uid       TEXT UNIQUE,
  phone_e164     TEXT UNIQUE,
  email          TEXT UNIQUE,
  full_name      TEXT,
  language       TEXT NOT NULL DEFAULT 'fr',
  market_code    TEXT NOT NULL DEFAULT 'CG',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at   TIMESTAMPTZ,
  disabled_at    TIMESTAMPTZ,

  CONSTRAINT user_accounts_reachable CHECK (phone_e164 IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE stations (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id  UUID REFERENCES operators(id) ON DELETE CASCADE,
  city_code    TEXT NOT NULL,
  name         TEXT NOT NULL,
  lat          DOUBLE PRECISION,
  lng          DOUBLE PRECISION,
  boarding_notes TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Roles are bundles of capability strings; checks are against capabilities,
-- never role names, so a new role is a configuration row (ADR-0011).
CREATE TABLE operator_staff (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id  UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
  roles        TEXT[] NOT NULL DEFAULT '{}',
  -- A vendor is scoped to their station(s): the Pointe-Noire agent must not
  -- be able to open the Brazzaville till.
  station_ids  UUID[] NOT NULL DEFAULT '{}',
  invited_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  accepted_at  TIMESTAMPTZ,
  revoked_at   TIMESTAMPTZ,

  UNIQUE (operator_id, user_id)
);

-- Our own staff. Three roles, not ten — ten roles for eight people is theatre,
-- and theatre that makes people share logins is worse than no separation.
CREATE TABLE platform_staff (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE UNIQUE,
  role        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at  TIMESTAMPTZ,

  CONSTRAINT platform_staff_role_known
    CHECK (role IN ('super_admin', 'operations', 'viewer'))
);

-- ── Compliance ──────────────────────────────────────────────────────────────

-- Selling seats on an uninsured coach is a liability we will not carry, so
-- expiry is tracked as data and enforced by a worker (03-operator-lifecycle §3.3).
CREATE TABLE kyb_documents (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id  UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  doc_type     TEXT NOT NULL,
  storage_key  TEXT NOT NULL,
  expires_at   TIMESTAMPTZ,
  verified_at  TIMESTAMPTZ,
  verified_by  UUID REFERENCES user_accounts(id),
  rejected_reason TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX kyb_documents_expiry_idx ON kyb_documents (expires_at)
  WHERE expires_at IS NOT NULL;

-- ── Catalogue ───────────────────────────────────────────────────────────────

-- Shared reference data, not tenant-scoped: two operators serving Pointe-Noire
-- must mean the same Pointe-Noire.
CREATE TABLE cities (
  code         TEXT PRIMARY KEY,
  market_code  TEXT NOT NULL,
  name_fr      TEXT NOT NULL,
  name_en      TEXT NOT NULL,
  lat          DOUBLE PRECISION,
  lng          DOUBLE PRECISION
);

CREATE TABLE routes (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id       UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  origin_city       TEXT NOT NULL REFERENCES cities(code),
  destination_city  TEXT NOT NULL REFERENCES cities(code),
  code              TEXT NOT NULL,
  distance_km       INTEGER,
  duration_minutes  INTEGER NOT NULL,
  -- Computed once per route and cached, so a thousand followers of one
  -- departure cost one Directions call, not a thousand (ADR-0014).
  polyline          TEXT,
  active            BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (operator_id, code),
  CONSTRAINT routes_distinct_endpoints CHECK (origin_city <> destination_city)
);

CREATE TABLE route_stops (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  route_id       UUID NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
  city_code      TEXT NOT NULL REFERENCES cities(code),
  station_id     UUID REFERENCES stations(id),
  sequence       INTEGER NOT NULL,
  offset_minutes INTEGER NOT NULL,
  -- A drop-off-only stop must not be sellable as an origin. Every naive model
  -- gets this wrong and every operator notices immediately.
  allows_boarding  BOOLEAN NOT NULL DEFAULT TRUE,
  allows_alighting BOOLEAN NOT NULL DEFAULT TRUE,

  UNIQUE (route_id, sequence)
);

-- ── Fleet ───────────────────────────────────────────────────────────────────

-- Immutable once a departure references it: editing a template creates a new
-- version, and sold departures keep the layout they were sold with.
CREATE TABLE seat_layouts (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id  UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  version      INTEGER NOT NULL DEFAULT 1,
  mode         TEXT NOT NULL DEFAULT 'bus',
  -- Ordered cabin sections (ADR-0017). One model serves a 2+2 coach, a
  -- VIP-front coach and a two-class aircraft.
  sections     JSONB NOT NULL,
  features     JSONB NOT NULL DEFAULT '[]',
  blocked      TEXT[] NOT NULL DEFAULT '{}',
  capacity     INTEGER NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (operator_id, name, version),
  CONSTRAINT seat_layouts_mode_known CHECK (mode IN ('bus', 'air')),
  CONSTRAINT seat_layouts_capacity_positive CHECK (capacity > 0)
);

CREATE TABLE vehicles (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id     UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  seat_layout_id  UUID NOT NULL REFERENCES seat_layouts(id),
  mode            TEXT NOT NULL DEFAULT 'bus',
  registration    TEXT NOT NULL,
  nickname        TEXT,
  model           TEXT,
  year            INTEGER,
  amenities       TEXT[] NOT NULL DEFAULT '{}',
  photo_asset     TEXT,
  status          TEXT NOT NULL DEFAULT 'active',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (operator_id, registration),
  CONSTRAINT vehicles_status_known CHECK (status IN
    ('active', 'maintenance', 'out_of_service', 'blocked_compliance')),
  CONSTRAINT vehicles_mode_known CHECK (mode IN ('bus', 'air'))
);

-- ── Scheduling ──────────────────────────────────────────────────────────────

CREATE TABLE departure_patterns (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id        UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  route_id           UUID NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
  rrule              TEXT NOT NULL,
  departure_time     TIME NOT NULL,
  default_vehicle_id UUID REFERENCES vehicles(id),
  fare_minor         BIGINT NOT NULL,
  currency           CHAR(3) NOT NULL,
  valid_from         DATE NOT NULL,
  valid_until        DATE,
  active             BOOLEAN NOT NULL DEFAULT TRUE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT departure_patterns_fare_positive CHECK (fare_minor > 0)
);

CREATE TYPE departure_status AS ENUM (
  'scheduled', 'delayed', 'boarding', 'departed', 'arrived', 'cancelled'
);

CREATE TABLE departures (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id            UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  route_id               UUID NOT NULL REFERENCES routes(id),
  pattern_id             UUID REFERENCES departure_patterns(id) ON DELETE SET NULL,
  vehicle_id             UUID REFERENCES vehicles(id),
  -- Captured at creation. Changing a template later must not rewrite a
  -- departure that already has bookings.
  seat_layout_id         UUID NOT NULL REFERENCES seat_layouts(id),

  departs_at             TIMESTAMPTZ NOT NULL,
  arrives_at             TIMESTAMPTZ NOT NULL,
  capacity               INTEGER NOT NULL,
  fare_minor             BIGINT NOT NULL,
  currency               CHAR(3) NOT NULL,
  status                 departure_status NOT NULL DEFAULT 'scheduled',
  seat_selection_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sales_close_at         TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT departures_arrive_after_depart CHECK (arrives_at > departs_at),
  CONSTRAINT departures_capacity_positive CHECK (capacity > 0)
);

CREATE INDEX departures_search_idx
  ON departures (route_id, departs_at)
  WHERE status <> 'cancelled';

CREATE INDEX departures_operator_day_idx ON departures (operator_id, departs_at);

COMMIT;
